export { AcceptIcon } from './AcceptIcon'
export { CloseIcon } from './CloseIcon'
export { DeleteIcon } from './DeleteIcon'
export { DownloadIcon } from './DownloadIcon'
export { EditIcon } from './EditIcon'
export { UploadIcon } from './UploadIcon'
export { LogoIcon } from './LogoIcon'
export { BigUploadIcon } from './BigUploadIcon'
